version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - CHANNEL_ID=${CHANNEL_ID}
      - PORT=8000
    restart: unless-stopped
    volumes:
      - ./bot.log:/app/bot.log
      - ./reactions_data.json:/app/reactions_data.json
